app:
  version: 0.0.3
  version_name: Controller's Control
  project_name: Ruslan Bank
  port: 4000
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dnlkk_db
    username: dnlkk
    password: dnlkkpass
ruslan: ruslan