app:
  version: 0.0.2
  name: Turnip's Repo
  port: 5000
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dnlkk_db
    username: dnlkk
    password: dnlkkpass
ruslan: ruslan