app:
  version: 0.0.3
  name: Controller's Control
  port: 4000
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dnlkk_db
    username: dnlkk
    password: dnlkkpass
ruslan: ruslan